# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2ef2def9303ec1c34565a63fc07e2ef7"
name = "fontify"
handle = "fontify-3"
application_url = "https://appfont--development.gadget.app/api/shopify/install-or-render"
embedded = true

[webhooks]
api_version = "2025-07"

[auth]
redirect_urls = [
  "https://appfont--development.gadget.app/api/connections/auth/shopify/callback"
]

[pos]
embedded = false

[build]
include_config_on_deploy = true
