# Learn more about working with Shopify TOML files with Gadget at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml

client_id = "7c18098fdad02b06cc625f7867f12ef8"
name = "fontifyy"
application_url = "https://fontifyy.gadget.app/api/shopify/install-or-render"
embedded = true

[auth]
redirect_urls = [ "https://fontifyy.gadget.app/api/connections/auth/shopify/callback" ]

[webhooks]
[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "https://webhooks.gadget-services.net/shopify/v1?domain=fontifyy.gadget.app"
topics = [ "shop/update", "app/uninstalled" ]
